### ISSUE TITLE
first/last step ignored style under shadow DOM

### ISSUE THREAD

**Issue by Zecat** [Zecat/paper-stepper#34]
``` css
#stepSelector > paper-horizontal-step:first-of-type ::content #leftConnectorLine,
#stepSelector > paper-horizontal-step:last-of-type ::content #rightConnectorLine {
  display: none;
}
```

This has no effect with shadow dom.
A work around could be to add the classes `.firstStep` and `.lastStep` to the involved steps and style directly in the step with `:host(.firstStep)` and `:host(.lastStep)` selectors.
