### ISSUE TITLE
Styling paper-stepper 

### ISSUE THREAD

**Issue by zfabic** [Zecat/paper-stepper#54]
Hi, 
how can I change the color of badge and next button? 
thnx

**Comment by Zecat** [comment]
There is no CSS variable for that yet, you can keep this issue opened until there are added.

The only workaround for now is:

``` css
<style is="custom-style">

  paper-stepper ::content #continueButton:not([disabled]){
    color: purple;
    background: pink;
  }
  paper-step ::content #stepLabel ::content #badge{
    background: pink;
    color: black;
  }
  paper-step ::content #stepLabel[saved] ::content #badge{
    background: pink;
    color: red;
  }
  paper-step ::content #stepLabel[opened] ::content #badge{
    background: green;
    color: blue;
  }
  paper-step ::content #stepLabel[selectable]:not([opened]):not([saved]) ::content #label:hover #badge{
    background: red;
    color: white;
  }

</style>
```

enjoy!
